version: "3.8"
services:
  setelorderservice:
    container_name: setelorderservice
    image: setelorderservice
    build: ./setel-order-service
    depends_on:
      - mongo
      - setelpaymentservice
    external_links:
      - mongo
    ports:
      - 3000:3000

  setelpaymentservice:
    container_name: setelpaymentservice
    image: setelpaymentservice
    build: ./setel-payment-service
    ports:
      - "3001:3001"

  setelweb:
    image: setelweb
    container_name: setelweb
    build: ./setel-web-ui
    ports:
      - "3002:3002"
    stdin_open: true

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
